apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monorepo-dev
resources:
  - ../../base
images:
  - name: app-demo
    newName: quay-rrkn9.apps.cluster-rrkn9.rrkn9.sandbox449.opentlc.com/monorepo-lab/app-demo
    newTag: 7e2de66e4cbb5fcf06e3e1d4ba04cbde59bb9677
configMapGenerator:
  - name: app-demo-config
    literals:
      - APP_NAME=app-demo
      - APP_VERSION=0.1.0
      - ENVIRONMENT=dev
      - IMAGE_TAG=0.1.0
generatorOptions:
  disableNameSuffixHash: true
