apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monorepo-dev
resources:
  - ../../base
images:
  - name: app-demo
    newName: quay-f6hgx.apps.cluster-f6hgx.f6hgx.sandbox952.opentlc.com/monorepo-lab/app-demo
    newTag: 0.1.0
configMapGenerator:
  - name: app-demo-config
    literals:
      - APP_NAME=app-demo
      - APP_VERSION=0.1.0
      - ENVIRONMENT=dev
      - IMAGE_TAG=0.1.0
generatorOptions:
  disableNameSuffixHash: true
