apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monorepo-dev
resources:
  - ../../base
images:
  - name: app-demo
    newName: quay-rrkn9.apps.cluster-rrkn9.rrkn9.sandbox449.opentlc.com/monorepo-lab/app-demo
    newTag: 4866e2b30e7a7de1768b1d528712f467dc3c11df
configMapGenerator:
  - name: app-demo-config
    literals:
      - APP_NAME=app-demo
      - APP_VERSION=0.1.0
      - ENVIRONMENT=dev
generatorOptions:
  disableNameSuffixHash: true
