apiVersion: v1
kind: ServiceAccount
metadata:
  name: app-demo
  labels:
    app.kubernetes.io/name: app-demo
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: monorepo-lab

imagePullSecrets:
  - name: quay-runtime-pull
