apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  generateName: app-demo-ci-test-
  namespace: monorepo-cicd
  labels:
    app.kubernetes.io/name: app-demo
    app.kubernetes.io/component: ci-test
    app.kubernetes.io/part-of: monorepo-lab
spec:
  pipelineRef:
    name: app-demo-ci
  taskRunTemplate:
    serviceAccountName: pipeline
  params:
    - name: GIT_URL
      value: https://github.com/rubenito77/openshift-tekton-argocd-quay-monorepo.git
    - name: GIT_REVISION
      value: main
  workspaces:
    - name: shared-workspace
      volumeClaimTemplate:
        metadata:
          labels:
            app.kubernetes.io/name: app-demo
            app.kubernetes.io/component: ci-workspace
            app.kubernetes.io/part-of: monorepo-lab
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
  timeouts:
    pipeline: 20m0s
